name: Build and Deploy
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/vuepress-deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: username/repo
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn add vuepress && npx vuepress build docs
        BUILD_DIR: docs/.vuepress/dist
